FROM theflash2k/pwn-chal:latest

ENV CHAL_NAME=plusplus
COPY ${CHAL_NAME} .
COPY flag.txt .

RUN apt-get update && \
    apt-get install -y libfmt-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
