version: "3.9"
services:
  app:
    build:
      dockerfile: ./Dockerfile.dist
    networks:
      - internal
    ports:
      - "1337:1337"
  mongodb:
    image: mongo:4.4
    networks:
      - internal

networks:
  internal:
