FROM theflash2k/pwn-chal:py38

RUN apt update && \
    apt install -y gcc && \
    apt-get clean -y && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

ENV CHAL_NAME="chal.py"
COPY ${CHAL_NAME} .

COPY flag.txt .
RUN mv flag.txt /flag-`cat /dev/urandom | head -10 | md5sum | cut -d ' ' -f1`.txt
